services:
  - type: web
    name: ai-agent-app
    env: python
    buildCommand: "bash utils/build.sh"
    startCommand: "gunicorn app:app"
    pythonVersion: 3.10
    region: oregon
    envVars:
      - key: ENV
        value: production
